import type { Metadata } from "next"
import "@/src/app/globals.css"
import { Sidebar } from "@/src/widgets/sidebar"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export const ReportLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) => {
	return (
		<>
			<Sidebar />
			{children}
		</>
	)
}
