import type { Metadata } from "next"
import "@/src/app/globals.css"
import { Navbar } from "@/src/widgets/navbar"
import { SidebarLayout } from "@/src/widgets/sidebar-layout"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export const ReportLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) => {
	return (
		<div className="flex h-screen">
			<Navbar />
			<div className="flex-1 flex">
				<SidebarLayout>{children}</SidebarLayout>
			</div>
		</div>
	)
}
