import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/src/app/globals.css";
import { Navbar } from "@/src/widgets/navbar";
import { Sidebar } from "@/src/widgets/sidebar";
import { Devtools } from "@/src/app/layouts/Devtools";
import { Provider } from "@/src/app/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Devtools />
          <div className="flex h-screen">
            <Navbar />
            <Sidebar />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
};
