import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "@/src/app/globals.css";
import { Navbar } from "@/src/widgets/navbar";
import { Sidebar } from "@/src/widgets/sidebar";
import { Devtools } from "@/src/app/layouts/Devtools";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      {/* TODO: react-devtoolsが機能しないので一時退避 */}
      {/* <Script src="http://localhost:8097" /> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Devtools />
        <div className="flex h-screen">
          <Navbar />
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
};
