[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
tokio = {version = "1.43.0", features = ["full"]}
serde = {version = "1.0", features = ["derive"]}
sqlx={version="0.8.3", features=["postgres", "runtime-tokio-rustls", "uuid", "chrono"]}
dotenvy="0.15"