apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: daily-report
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/kmno4hno3/daily-report
          env:
            - name: TARGET
              value: "Rust Sample v1"