name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test1
      run: ls
    - name: test2
      run: cd backend
    - name: test3
      run: pwd
    - name: test4
      run: ls
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
